from __future__ import annotations

import hashlib
import math
import re
from collections import defaultdict
from copy import deepcopy
from typing import Any

from l1_data_processing.llm.client import LLMResponse


TOKEN_RE = re.compile(r"[\w\u4e00-\u9fff]+", re.UNICODE)


class FakeLLM:
    def __init__(self, preset_responses: dict[str, dict[str, Any]] | None = None, embedding_dimensions: int = 8) -> None:
        self.preset_responses = preset_responses or {}
        self.embedding_dimensions = embedding_dimensions
        self.calls: dict[str, int] = defaultdict(int)

    def complete(self, prompt: str, *, model: str) -> LLMResponse:
        self.calls["complete"] += 1
        text = self.preset_responses.get("complete", {}).get("text", "fake completion")
        return LLMResponse(text=text, data={}, prompt_tokens=len(prompt.split()), completion_tokens=len(text.split()), model=model)

    def structured(self, prompt: str, *, schema_name: str, model: str) -> LLMResponse:
        self.calls["structured"] += 1
        self.calls[f"structured:{schema_name}"] += 1
        default = {
            "one_liner": "Deterministic L1 base analysis",
            "summary": "A deterministic summary generated by FakeLLM for standalone L1 validation.",
            "key_points": ["stub content loaded", "fake llm used", "base schema produced"],
            "quotes": [],
            "entities": ["L1"],
            "base_tags": ["data-processing", "standalone"],
        }
        defaults_by_schema: dict[str, dict[str, Any]] = {
            "BaseAnalysis": default,
            "ChunkAnalysis": default,
            "ContentFilter": {"ignore": False, "reason": "", "value": "normal"},
        }
        data = self.preset_responses.get(schema_name, defaults_by_schema.get(schema_name, default))
        if isinstance(data, list):
            index = self.calls[f"structured:{schema_name}"] - 1
            data = data[min(index, len(data) - 1)]
        data = deepcopy(data)
        return LLMResponse(
            text="",
            data=data,
            prompt_tokens=len(prompt.split()),
            completion_tokens=sum(len(str(value).split()) for value in data.values()),
            model=model,
        )

    def embed(self, text: str, *, model: str) -> list[float]:
        self.calls["embed"] += 1
        vector = [0.0 for _ in range(self.embedding_dimensions)]
        tokens = TOKEN_RE.findall(text.casefold())
        for token in tokens:
            digest = hashlib.sha256(f"{model}:{token}".encode("utf-8")).digest()
            index = digest[0] % self.embedding_dimensions
            sign = 1.0 if digest[1] % 2 == 0 else -1.0
            vector[index] += sign
        magnitude = math.sqrt(sum(value * value for value in vector)) or 1.0
        return [round(value / magnitude, 6) for value in vector]
